### ISSUE TITLE
Order of resolving keywords

### ISSUE THREAD

**Issue by mplain** [cryogen/throneteki#1275] opened 2017-07-31 17:07 UTC
This just in! Ser Gregor attacks, unopposed, gets intimidate from Lord Renly's Ride, wins, intimidates Victarion, pillages Victarion, kills Victarion, Asha remains standing. One of those rare cases when the order of keywords could matter quite a lot.

Suggestion: Change the default order of resolving keywords to pillage first, then intimidate.

**Comment by cryogen** [comment] 2017-07-31 17:11
Duplicate of #526

**Closed by cryogen** 2017-07-31 17:11 UTC

**Comment by mplain** [comment] 2017-07-31 17:30
To clarify, I suggest changing th default order of resolution, not making keywords optional and prompting the order every time. And if/when you get to implement the latter, I suggest giving an option to set the default order to be used for each user, without prompts.

**Comment by cryogen** [comment] 2017-07-31 17:31
I know, but that's what we're going to end up doing, which will also fix this
