### ISSUE TITLE
Backgrounds

### ISSUE THREAD

**Issue by khyinn** [cryogen/throneteki#1190] opened 2017-07-19 15:48 UTC
Hey ! Here are some good backgrounds to test for throneteki :) Maybe you can test them and make them optional in user settings page.

![baratheon](https://user-images.githubusercontent.com/25751963/28376278-08980032-6caa-11e7-8b36-3e9015eee3ba.jpg)
![greyjoy](https://user-images.githubusercontent.com/25751963/28376276-0890a3be-6caa-11e7-8455-9aea4eabb4e7.jpg)
![lannister](https://user-images.githubusercontent.com/25751963/28376279-08983124-6caa-11e7-9461-1a16f19596fa.jpg)
![martell](https://user-images.githubusercontent.com/25751963/28376275-088f3c5e-6caa-11e7-91db-2c46a846fe9c.jpg)
![night s watch](https://user-images.githubusercontent.com/25751963/28376274-088cc9e2-6caa-11e7-8b15-771e1106c803.jpg)
![stark](https://user-images.githubusercontent.com/25751963/28376277-0890b642-6caa-11e7-8fdb-00b8fd85659e.jpg)
![targaryen](https://user-images.githubusercontent.com/25751963/28376280-08a7dc50-6caa-11e7-9f05-dc4209c3273a.jpg)
![tyrell](https://user-images.githubusercontent.com/25751963/28376281-08bfbafa-6caa-11e7-8ddc-997f5dc3e583.jpg)

**Comment by cryogen** [comment] 2017-07-19 16:03
Woah. These are gorgeous. Are these your work?

**Comment by khyinn** [comment] 2017-07-19 16:13
No, they aren't. They are based on Sasha Vinogradova's work, with the right to modify and use. So i've modified them to remove text (for other languages than english). The Night's Watch background is a modification of a wallpaper found on internet and free to use. I've removed the third eye of the three-eyed raven to make a crow :)

**Comment by cryogen** [comment] 2017-07-19 17:01
Ah Ok, That sounds fine.  Can you link me to the license anywhere? And maybe to the original source so I can credit it

**Comment by khyinn** [comment] 2017-07-19 17:59
Sure : http://www.sashavinogradova.com for the original work.

**Comment by zacchiro** [comment] 2017-07-20 08:39
so what's the idea about *using* these in practice here?
use the background of the faction of the player who initiated any given game? (that sounds sensible to me)

**Comment by cryogen** [comment] 2017-07-20 08:40
I was just going to make then configurable for anyone to have any.  We could default to the faction you're playing (since it's per person it could be different for each player)

**Comment by zacchiro** [comment] 2017-07-20 08:44
Oh, so it'd be different backgrounds seen by different players. Sure, why not.
Although I admit the idea of making it the same for the two players, and depending on who initiated the game has some appeal. It will feel like playing "at home", or playing in "opponent's territory" :-) Also, it will allow people to see all these gorgeous backgrounds over time.
Just throwing the idea in the bucket, these are so nice that either solution is fine :-) Thanks @khyinn !

**Comment by khyinn** [comment] 2017-07-20 09:15
@cryogen : don't forget to add an option for "no background", i know some players don't want to use a custom background.
And for backgrounds, please add transparency like in [https://github.com/cryogen/throneteki/pull/431/commits/9241c38700ad99164dac1a737e81b7db458c64ea](url) but make it only if a custom background is selected.

**Comment by zacchiro** [comment] 2017-07-20 14:22
so, the works are here https://github.com/cryogen/throneteki/issues/1190#issuecomment-316646238 , but I couldn't find any mention of an actual license.

@khyinn : can you clarify if you found a license, and if so where, or how else you concluded that these works can be modified/reused?

**Comment by khyinn** [comment] 2017-07-20 14:50
I didn't found any license. The author posted the PSD for this a while ago on https://www.behance.net/gallery/3985601/Game-of-thrones-wallpapers so everyone can use and modify this but the link is now dead and he doesn't reply to my emails. I think we can use this with giving original credits.

**Comment by zacchiro** [comment] 2017-07-23 09:28
Duplicate of #430.

(We will keep track in #430 of the general feature of adding customizable user backgrounds. This bug, referenced from there, will keep pointers to some of the available backgrounds.)

**Closed by zacchiro** 2017-07-23 09:28 UTC
