### ISSUE TITLE
Fealty not reducing

### ISSUE THREAD

**Issue by PeteCrighton** [cryogen/throneteki#1439] opened 2017-09-14 00:13 UTC
I don’t know if this was due to a certain combo, if we did something wrong, or if _Fealty_ simply does not work as intended. My opponent played a _Baratheon/Fealty_ deck and none of his cards got reduced by _Fealty_ (although they should have), so he had to manually adjust his gold pool every time.

**Comment by ystros** [comment] 2017-09-14 00:57
Thanks for the report! I'm not able to reproduce a problem with Fealty.

Fealty is an Action, so it isn't automatically applied when marshaling cards nor prompted like a Reaction or Interrupt. Like other Actions on the site, it must be explicitly activated by clicking on the Fealty card, then on the "Kneel your faction card" option in the menu that pops up. Then a message like "PlayerX uses Fealty to kneel their faction card and reduce the cost of the next loyal card by 1".

Do you know if your opponent was clicking on Fealty to activate it? Did you see any messages in the chat log about it reducing cost?

**Comment by PeteCrighton** [comment] 2017-09-14 01:08
The faction card was definitely knelt. But maybe he accidentally knelt his faction card directly instead of activating _Fealty_. I’ll ask him if he still remembers.

I don’t remember the message in the log. Although not quite certain, I would say it did not appear.

**Comment by zacchiro** [comment] 2017-09-14 06:20
Kneeling the faction card directly rather than clicking on Fealty and picking the "kneel faction card" sounds like the most likely explanation of this.

**Comment by cryogen** [comment] 2017-09-16 12:53
Closing this as by all accounts Fealty is working correctly.  Please reopen if you are able to reproduce this in the future

**Closed by cryogen** 2017-09-16 12:53 UTC
Labels: Unable to reproduce

**Comment by PeteCrighton** [comment] 2017-09-17 13:32
I can confirm that’s what happened. Sorry for the false alarm.
