### ISSUE TITLE
The Iron Bank

### ISSUE THREAD

**Issue by chumbert1834** [cryogen/throneteki#1748] opened 2018-02-15 05:35 UTC
The Iron Bank is not programmed in at all aside from the bestow option. There is no prompt in the reaction window, and when I click on the card there are no options to trigger the gold add. There is also no easy way to manually work it, since I can only set the gold with the bestow command and there is no command to simply set the gold value. I cannot subtract the gold I spend from it.

The manual workaround would be ok, (say, just a /gold x command) but putting in a way to spend gold from the card would be even better.

**Comment by ystros** [comment] 2018-02-15 05:46
Thanks, but this is a direct duplicate of an existing issue (#1628). Closing this one.

**Closed by ystros** 2018-02-15 05:46 UTC

**Comment by ystros** [comment] 2018-02-15 05:49
Also, there is an existing command to put gold on a card without bestowing it: /token gold X

**Comment by chumbert1834** [comment] 2018-02-15 06:08
Great, didn't know that one. Thanks!
