### ISSUE TITLE
Steward At The Wall & The Wall Strength Issue

### ISSUE THREAD

**Issue by doomnote** [cryogen/throneteki#203] opened 2017-01-10 21:50 UTC
Attacking with just 1 Steward at the Wall while having The Wall out shows the correct strength buff on Steward (2) but the challenge goes through with (4) strength. Castle Black was also out at this time, but unused, in case that has any effect.

**Comment by cryogen** [comment] 2017-01-11 08:34
I can't reproduce this, so chances are the circumstances are slightly more involved.  Any idea on what else was going on at the time?

**Comment by ystros** [comment] 2017-01-13 18:37
This may or may not be fixed with the way strength buffing works now.

**Comment by cryogen** [comment] 2017-01-18 08:39
I'm going to assume this is fixed until such time as it happens again and this can be reopened :)

**Closed by cryogen** 2017-01-18 08:39 UTC
