### ISSUE TITLE
Adding i18n-node for localization

### ISSUE THREAD

**Issue by khyinn** [cryogen/throneteki#423] opened 2017-02-19 08:37 UTC
Just something i've told to cryogen few days ago. Offer the possibility to play in our own language.
For cards, we have the possibility to use some "resource overriding" to use our own scans but for the UI language, it's not so easy and needs code modifications to make it happen.

That's where i18n-node comes in.

Look at https://github.com/mashpie/i18n-node for details.

**Comment by cryogen** [comment] 2017-03-08 10:02
A couple of people have expressed an interest in localising the site.  It would depend on getting cards in the languages concerned and also implementing some framework for getting the site and game engine translated to those languages.  It's a great idea but it's a lot of work and I'm not sure it's likely to happen short to medium term

**Comment by zacchiro** [comment] 2017-07-22 11:26
Duplicate of #994

**Closed by zacchiro** 2017-07-22 11:26 UTC
Labels: enhancement
