### ISSUE TITLE
Annals of Castle Black interrupts

### ISSUE THREAD

**Issue by chumbert1834** [cryogen/throneteki#1124] opened 2017-07-06 23:29 UTC
During a turn when The Annals of Castle Black is revealed, players are not asked to activate interrupt events (like The Hand's Judgment and Treachery) as if they were in their hand. This makes using the plot difficult and clunky with lots of manual rewinding, since without this window the events resolve immediately

**Comment by DukeTax** [comment] 2017-07-06 23:30
Thanks for reporting. This fix is already in and will be deployed soon.

#1077

**Comment by ystros** [comment] 2017-07-07 00:17
As mentioned, there's a fix up for review. This is also an exact duplicate of #1048. Closing.

**Closed by ystros** 2017-07-07 00:17 UTC
