### ISSUE TITLE
Rakharo + Desmera Redwyne

### ISSUE THREAD

**Issue by Redal59** [cryogen/throneteki#1588] opened 2017-11-10 13:04 UTC
Firstly just noticed Rakharo's reaction triggers but does not add the power to him.  

Secondly, Desmera Redwyne has been triggering off every card leaving play while she is on the board. Killed for claim, Valar, discarded etc,  whether they are in a challenge or not.

**Comment by DukeTax** [comment] 2017-11-10 14:35
Thanks for reporting.

- I can't reproduce the Rakharo issue. Can you elaborate on the circumstances in which it happened? Maybe there was a 'cannot gain power'-effect active (Your King Commands It, Tokar)?

- A fix is in for the Desmera issue (#1586).

**Comment by DukeTax** [comment] 2017-11-18 21:22
Closing this as Demera has been fixed, and without more information, I suspect the Rakharo issue wasn't a bug.

@Redal59 If you happen upon the Rakharo issue again you can still reply here.

**Closed by DukeTax** 2017-11-18 21:22 UTC
Labels: Unable to reproduce
