### ISSUE TITLE
Ward vs. Valar / Confiscation

### ISSUE THREAD

**Issue by mplain** [cryogen/throneteki#607] opened 2017-03-16 17:17 UTC
1) My opponent Wards my duped Arya, I reveal Confiscation, he reveals Valar, I go first, resolve Confiscation first, Valar resolves, Arya dies.

I assume you coded it so that a Warded character ignores dupes, but the check is made at some point prior to the resolution of plot effects.

Also I might want to save my stolen Arya from Valar if I planned to confiscate Ward later, a turn after Valar.

2) I reveal Confiscation and discard Ward from my Paxter, then during plot phase he does not give me +1 gold (i'm not sure if he gave the bonus gold to my opponent that turn).

I think I can see a pattern here: certain values are calculated before the resolution of plots.

**Comment by ystros** [comment] 2017-03-17 08:25
So far I've not been able to reproduce either of these issues. I've added tests around the basic interactions in #611, and Paxter survived the Valar when Confiscation went first, and provided the gold bonus on the same turn he was de-Warded. Was there anything else strange going on in these games?

Having the ability to trigger your dupe while you don't control the character is definitely valid, though, and what you'd want to do in your scenario. Implementing it may be... tricky.

**Comment by cryogen** [comment] 2018-02-23 14:28
Closing this as the original issue hasnt been reproducible.  Will raise the other feature request as a separate issue

**Closed by cryogen** 2018-02-23 14:28 UTC
