### ISSUE TITLE
Margaery (AMAF) with "King"-Attachments

### ISSUE THREAD

**Issue by Hyphistos** [cryogen/throneteki#865] opened 2017-05-09 14:00 UTC
It is my understanding that Margaery should trigger when a unique character who is not King or Lord itself, but has an attachment that adds one of these traits, is killed. I did not test it for other constellations, but it did not trigger for Dalla with King Beyond the Wall.

**Comment by cryogen** [comment] 2017-05-10 07:58
Similar to #837

**Comment by zacchiro** [comment] 2017-07-24 16:59
Duplicate of #837.
(whose title I've just generalized)

**Closed by zacchiro** 2017-07-24 16:59 UTC
