### ISSUE TITLE
Fortified position should make players unable to put bestow on characters

### ISSUE THREAD

**Issue by JakobWah** [cryogen/throneteki#1704] opened 2018-01-22 16:40 UTC
http://www.cardgamedb.com/forums/index.php?/topic/38604-bestow-and-fortified-position/ At the moment players are allowed to put gold for bestow on characters even though their text box is blank when entering play by fortified position. According to the linked thread this should not be the case.

**Comment by DukeTax** [comment] 2018-01-22 17:11
Thanks for reporting. :) This is a duplicate of #1462.

**Closed by DukeTax** 2018-01-22 17:11 UTC
