### ISSUE TITLE
unsullied strength effect issue

### ISSUE THREAD

**Issue by GeorgeG1984** [cryogen/throneteki#874] opened 2017-05-11 20:43 UTC
Hello i had an issue in a game with the unsullied -1 strength effect was taking effect in challenges after they had initially attacked. no other strength modifers were on the board , plots or via events , no dany on board.
just wanted to report, great job on throneteki.

**Comment by zacchiro** [comment] 2017-07-22 11:20
I regularly play Unsullied and I've never seen this, at least in recent times.
Have you seen it again recently, @GeorgeG1984 ?
Either way, if it's an actual issue, we need more info to make it reproducible, because it's currently not.

**Comment by zacchiro** [comment] 2017-09-12 07:46
closing old unreproducible bug report, please reopen if you encounter this again in the wild!

**Closed by zacchiro** 2017-09-12 07:46 UTC
Labels: Need info, Unable to reproduce
