### ISSUE TITLE
Two roseroads in setup

### ISSUE THREAD

**Issue by thanivar** [cryogen/throneteki#1755] opened 2018-02-20 19:59 UTC
In a game i saw someone missclick in setup and placed 2 roseroads and viper instead of viper, orphan, and 1 roseroad. No idea how it happened but i told them i would report it. 

Was martel rains against targ X. (Nasty4g with martel against Rein with targ)

**Comment by jbrz** [comment] 2018-02-20 20:05
@thanivar Did he drag the 2nd roseroad from hand into play?  There's nothing that restricts you from manually breaking setup rules.

**Comment by thanivar** [comment] 2018-02-20 20:50
mmmm you would have to ask him (nasty4g), but from his reaction it wasn't intentional.

**Comment by zacchiro** [comment] 2018-02-23 16:34
This is not reproducible right now, so I'm closing it. If anyone finds a way to actually reproduce this, please reopen—ideally with precise steps on how it happened, because it's currently a mistery :-)

**Closed by zacchiro** 2018-02-23 16:34 UTC
