### ISSUE TITLE
Plaza of Pride not taking cost into account

### ISSUE THREAD

**Issue by IMABUNNEH** [cryogen/throneteki#1226] opened 2017-07-23 11:14 UTC
Myself and my opponent were able to use Plaza of Pride to discard a 1 cost card to stand a 7 cost character.

**Comment by DukeTax** [comment] 2017-07-23 12:14
I'm quite sure I've seen this happen before myself, but I can't reproduce it.

**Comment by zacchiro** [comment] 2017-09-12 07:46
closing old unreproducible bug report, please reopen if you encounter this again in the wild!

**Closed by zacchiro** 2017-09-12 07:46 UTC
Labels: Unable to reproduce
