### ISSUE TITLE
Burning a character with White Shadows out has them enter play with 0 STR.

### ISSUE THREAD

**Issue by DukeTax** [cryogen/throneteki#1113] opened 2017-07-05 10:43 UTC
Happened with Dracarys! vs Quentyn Martell.

**Comment by ystros** [comment] 2017-07-06 16:48
I think this is the same as #844, rather than an issue specific to White Shadows.

**Comment by zacchiro** [comment] 2017-07-21 20:59
Duplicate of #844 (which I've just retitled to be more general).

**Closed** 2017-07-21 21:00 UTC
