### ISSUE TITLE
Flea Bottom Bastard doesn't contribute +3 str to dom

### ISSUE THREAD

**Issue by IMABUNNEH** [cryogen/throneteki#1148] opened 2017-07-11 12:24 UTC
The +3 strength during dom from Flea Bottom Bastard isn't applied until after the winner of Dom is determined. It should already be present at that point.

**Comment by ystros** [comment] 2017-07-11 16:43
When did this bug occur for you? I believe it existed prior to this weekend but a fix should have gone out for it along with The Red Wedding cards. Were there any other weird circumstances when it happened (other dominance modifying cards for instance)?

Offhand I can't reproduce it (0 gold, 1 STR + 3 from Flea Bottom Bastard, +2 STR from Hedge Knight = 6 total for dominance):
![screen shot 2017-07-11 at 9 37 14 am](https://user-images.githubusercontent.com/145077/28079428-415abd80-661d-11e7-817a-1dc9d79987f0.png)

**Comment by ystros** [comment] 2017-07-12 07:26
The problem was that some games on the site were getting the old code prior to the fix and some were getting the newer code. All games should be on the newer code now, so this should be fixed.

**Closed by ystros** 2017-07-12 07:26 UTC
